version: '3.9'
services:
  clicker-db:
    image: "postgres:14.5-alpine"
    container_name: clicker-db
    expose:
      - 5432
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=royal-db
      - POSTGRES_PASSWORD=clickerroyale
      - POSTGRES_USER=admin

  clicker-backend:
    container_name: clicker_backend
    build:
      context: ./clicker_backend
      dockerfile: Dockerfile
    depends_on:
      - clicker-db
    links:
      - clicker-db
    expose:
      - 3001
      - 5432
    volumes:
      - sharedVolume:/clicker_backend/shared_volume

  clicker-frontend:
    container_name: clicker_frontend
    build:
      context: ./clicker_frontend
    ports:
      - '3000:3000'
    expose:
      - 3000
    volumes:
      - sharedVolume:/clicker_frontend/src
volumes:
  sharedVolume:
